export enum CONSTANTS {
  CreatedAt = 'createdAt',
  Value = 'value',
  GET = 'GET',
  Email = 'email',
  Password = 'password',
  PasswordRepeat = 'passwordRepeat',
  PasswordConfirm = 'passwordConfirm',
  OldPassword = 'oldPassword',
  NewPassword = 'newPassword',
  Common = 'common:',
  None = 'none',
  Type = 'type',
  Bio = 'bio',
  Chat = 'chat',
  Screen = 'screen',
  SearchLocation = 'searchLocation',
  Username = 'username',
  ProfileDots = 'profile:',
  SettingsDots = 'settings:',
  ReactNative = 'React Native',

  Title = 'title',
  Settings = 'settings',

  SGathering = "'s Gathering",
  Active = 'active',
  Outdoors = 'outdoors',
  Indoors = 'indoors',
  Name = 'name',
  Description = 'description',
  Setting = 'setting',
  Virtual = 'virtual',
  Growth = 'growth',
  Fun = 'fun',
  Other = 'other',
  Pro = 'pro',
  Casual = 'casual',
  All = 'all',
  Men = 'men',
  Women = 'women',
  Children = 'children',
  Family = 'family',
  Approach = 'approach',
  Audience = 'audience',
  Size = 'size',
  Date = 'date',
  OneOff = 'oneOff',
  Today = 'today',
  Tomorrow = 'tomorrow',
  DateTimePicker = 'dateTimePicker',
  Default = 'default',
  Time = 'time',
  Location = 'location',
  DefaultTheme = 'defaultTheme',
  EmailEdit = 'email-edit',
  AccountKey = 'account-key',
  FormatLetterCase = 'format-letter-case',
  Palette = 'palette',
  Library = 'library',
  Logout = 'logout',
  Capture = 'capture',
  Cover = 'cover',
  Scale = 'scale',
  AccountRemove = 'account-remove',
  CameraPlus = 'camera-plus',
  SelectImage = 'selectImage',
  TakeImage = 'takeImage',
  Photo = 'photo',
  SelectionLimit = 'selectionLimit',
  AccountOutline = 'account-outline',

  En = 'en',
  Lt = 'lt',

  RapidHost = 'x-rapidapi-host',
  RapidHostValue = 'referential.p.rapidapi.com',
  RapidKey = 'x-rapidapi-key',
  RapidURL = 'https://referential.p.rapidapi.com/v1/city',
  RapidFields = 'iso_a2',
  RapidLimit5 = '5',

  PolicyURL = 'https://kilo.health',

  DefaultUsername = 'Happy Panda',
  DefaultImage = 'https://lh3.googleusercontent.com/ogw/ADea4I59XeOr6V5p2vPtCsE9S2ZnJQKTl5PgeER2K0CX=s192-c-mo',

  Heart = 'account-heart',
  AccountPlus = 'account-plus-outline',
  Account = 'account',
  AccountHeart = 'account-heart',
  AccountEdit = 'account-edit',
  AccountCog = 'account-cog',
  Campfire = 'campfire',
  Close = 'close',
  Eye = 'eye-outline',
  EyeOff = 'eye-off-outline',
  ArrowLeft = 'arrow-left',
  Send = 'send',
  AccountSearch = 'account-search',
  CloseThick = 'close-thick',
  CalendarMonth = 'calendar-month',
  MapMarker = 'map-marker',
  MapMarkerPlus = 'map-marker-plus',
  Clock = 'clock',
  Plus = 'plus',
  Message = 'message',
  EmoHappy = 'emoticon-happy',
  AccountMultiple = 'account-multiple',
  Pen = 'pen',
  ChevronRight = 'chevron-right',
  Image = 'image',

  Ios = 'ios',

  Bold = 'bold',
  Transparent = 'transparent',
  Padding = 'padding',
  Height = 'height',
}
